name: Deploy to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3 to use Node.js 20

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA3pSfdc4De7bjaIHz79zUXOGwiACABtnu/stLo3Fc5eeWHJZyvbWU
iihw7AEjN4oqgscNtWJ2ayuSK8k/Rl//4MiSoUie2SGuKkwDi9xjVfkohV7ACcsNLjaP7m
A8B0NDRHJFXKQs0rwu2tnv8pZfFtQb0QbV21xu+Ow8sJSSxLwDhP1n7bwQ294mZGdRryYa
hrS/LQs3FvHGGD8kCsHIvMrZKISkH7ldjEK8qBThrczYSCWDdA1FY/0X7lXFUSiWfBI5/c
3Bn+9gh+5BDKTiZhOqDMrsr6hlq7Bhjv+jOko+CM0QN+T0aQbEFr8ck7ezrm/0qGa+UPh1
fiURqpYPsHEMVnJPCbOdjGyT7CBINvgtQCI92HZ35fM4Gp6IuOjGf4GyUayYxeTDcbi/gJ
pczoJkAJQ0+B2fb7lczrQdaqWfAj/iLlok84wYLv6vaaJ6mAYpiSizRvRagct6lqJcVkOo
xYbgOcLc0sCYITFzm1soSM1zfMYFfc5wTUuK8l7leP3D2xWiRqOXb9NW7hS0H5yk6+SY1E
IPZZYn4KHI3MnSWVQZsMY+jouiD2gUwVSw1q3mmt1YDuhZAlVZOfsGo1rzu0PyVfFGl9Iy
vsfH9Wtq/WAVWiyhUxr9IHdHHIi3qGO92deV/vBWUiJNR51GhyZLyVlVvK0hZMXa+lg9DE
0AAAdQG2subRtrLm0AAAAHc3NoLXJzYQAAAgEA3pSfdc4De7bjaIHz79zUXOGwiACABtnu
/stLo3Fc5eeWHJZyvbWUiihw7AEjN4oqgscNtWJ2ayuSK8k/Rl//4MiSoUie2SGuKkwDi9
xjVfkohV7ACcsNLjaP7mA8B0NDRHJFXKQs0rwu2tnv8pZfFtQb0QbV21xu+Ow8sJSSxLwD
hP1n7bwQ294mZGdRryYahrS/LQs3FvHGGD8kCsHIvMrZKISkH7ldjEK8qBThrczYSCWDdA
1FY/0X7lXFUSiWfBI5/c3Bn+9gh+5BDKTiZhOqDMrsr6hlq7Bhjv+jOko+CM0QN+T0aQbE
Fr8ck7ezrm/0qGa+UPh1fiURqpYPsHEMVnJPCbOdjGyT7CBINvgtQCI92HZ35fM4Gp6IuO
jGf4GyUayYxeTDcbi/gJpczoJkAJQ0+B2fb7lczrQdaqWfAj/iLlok84wYLv6vaaJ6mAYp
iSizRvRagct6lqJcVkOoxYbgOcLc0sCYITFzm1soSM1zfMYFfc5wTUuK8l7leP3D2xWiRq
OXb9NW7hS0H5yk6+SY1EIPZZYn4KHI3MnSWVQZsMY+jouiD2gUwVSw1q3mmt1YDuhZAlVZ
OfsGo1rzu0PyVfFGl9IyvsfH9Wtq/WAVWiyhUxr9IHdHHIi3qGO92deV/vBWUiJNR51Ghy
ZLyVlVvK0hZMXa+lg9DE0AAAADAQABAAACACZdN572g2MvgsLgo0sUpQXdYLAQZgDIT4lb
QQ5K29hEsnr684v/YDrv/YawK4HHLsybwqEg94hBWlBxv5ZBtbjo2V0zRy3lwD9KGtJgij
6nU3SpgDAv73WnsedEbxRRY6bIi2wMYC1ygiD2r4UApiMpLCI7K2FD7Vy6WzuUYDfIsFKb
2u3/HGjJQZTMuieWSbwuK0V4SWaLBbnoKC4yeIcR75wsQJ23NYiXeC0AbGWoiR7mWGIIZ4
10ckuCPSBf/pAkFBrK/DS07c6AInYrdVpiyUyrLWCZheyx2h7rsRa69TZPIhyAOiBgKixB
hItxfmbypRjhnKwYJyg2+3SLqOhONAQ6YeBhkRXKMnxca4B94fmiN8TxPE2HrvI9jaDOmE
1b+P8QXCtjxhIZ9ciSuzVJRL7aWQB3Ky/Vi/xmov0+Hs9L9F6VC2/StGPGaclW+FWoJNN2
xaATPZ+KEFP3k2SQ2vY4eoXo0EC9CAW5r7H1gnv0oir6Q1oOYcp0nlDpiEkMdFl8fvi2aa
PlgNU5sDfpibeOd+tQgg8xH0mtS/IDDMOPu+sqUaFv+6qSnuR+PYOTMNI838WxTDW3aqoU
zNzgE09+dSBQREETRlsTbWQ+N8WuMM7LnwSne4N80RozWMOy1F4KoOnfP6PRAKaquNm4I7
qsQxy/ZV412bKx9iwBAAABAF7WPThJWEyRFB7KlFzso5ClyqQ4tWswiwXL5kOdCw9LfV2c
v74BqUM05Tdn2oe9e+XklO8eQRSLumieMWoC7lCXPUX4CD05PTkQc1LOal+SdPu9OsA9jG
QbIPLpFumMCvjEX0yq5EkoVU7H9FeXCzz8yPGqTHIQgUH8L5semq73DoZfheX4tmXYQxMQ
rxoqH7esgfsd7VfhzLI8bbovZRHKUqvgi3iTTc6/IADy11QpnrTl5SbCrTb8Xn5QfutIpM
Zse5S3YQWhcgq/eSUBJ2k0qm/WsC7yW3BYoUOQ6qXNsBJO+Mq7YUWTMfUC70g35WzPDihw
JTvD2sw+KmlQK88AAAEBAPnllYN/CV7KW6egJB4RAP97/VC9U406qHlvriGnXWYnuh7XV8
lWArs3V3V5gJyGbl9ebWe1Vuew8OEd5dxoZejO09rhssc/FqpPSsmwngousskIqF4TFlv9
hYD8rkuhnPOcezEZQmg1Klt2SNzfNJ81V2A6g+J1+RGBlfJqTECetgZltiXt34gKoDDbXI
sYi76wQIy+EYhFFvVzQcnCUY7mU3WRtxyE9VjpEzxJXhl0KwcsytE3sL4oe6TqHYbDNX1t
p/FkEc0VezGgW6dvIgBFjoGcLaySHcgOtvzz885jOyEEs3hYs0hIlWw7ELkfw30/D7Hb5J
xofxaRatNNjjUAAAEBAOQEQD5ykUu6AQMiC9c/+73k8X/iQrZyNWh1KXwodydmS9Dxkfhm
ZOLOU43KqAxBhni7a07EpHhjGJK4VqchtmOzmAgXc2IU5C0cgbImUzFHQg4dWgBytXiBi7
V2szgaihPdt2bNh5iFWziyGY+PyT6/yEp0cs40aA2GcquaW/f+i2FOx7o1vDK0Gf0G7cOA
WIqE9jeYLpdm9beVjeD2mthSIMgPtKBerjFWesJslg+twzRnvZtPcs8h3OhESieYmokIQs
ipIHvWyt7FjVRe0PrUHvXlTH2SGlgBBNjcbYWvSAMVmEDN35ibzzCH4zvpvuyNYv3TkPAK
LN0ou341KLkAAAAbc2hhcm1hLm9mZmljaWFsMTJAZ21haWwuY29t

    - name: Deploy code to VPS
      run: |
        ssh root@146.190.11.0 'cd /freshfarmsbackend && git pull origin dev && yarn && pm2 restart all'
